export * from "./types.ts";
export type { Repository, CacheEntry } from "./storage/repository.ts";
export { isLeboncoinListingPage, parseLeboncoin, parseLeboncoinHtml } from "./extraction/leboncoin.ts";
export { detectSite, isListingPage } from "./extraction/sites.ts";
export { isSelogerListingPage, parseSeloger, parseSelogerHtml } from "./extraction/seloger.ts";
export { parseBienici } from "./extraction/bienici.ts";
export { isCityaListingPage, parseCitya } from "./extraction/citya.ts";
export { detectCommuneDoubt } from "./extraction/commune-doubt.ts";
export type { CommuneDoubt } from "./extraction/commune-doubt.ts";
export { geocode, geocodeSuggest, correctedLocation } from "./enrichment/geocode.ts";
export type { GeocodeSuggestOptions } from "./enrichment/geocode.ts";
export { stripAccentsLower, fixMojibake } from "./extraction/mapping.ts";
export { parseDvfCsv, computeMarketStats, fetchCommuneSales, DVF_YEARS, haversineM, propertySaleHistory, buildSaleTimeline } from "./enrichment/dvf.ts";
export type { SaleTimeline } from "./enrichment/dvf.ts";
export { fetchRisks } from "./enrichment/risks.ts";
export type { FetchRisksOptions } from "./enrichment/risks.ts";
export { fetchCommuneInfo, citycodeFromLatLon, postalCodeOfCity } from "./enrichment/commune.ts";
export type { FetchCommuneInfoOptions } from "./enrichment/commune.ts";
export { fetchPluZone, explainPluZone } from "./enrichment/plu.ts";
export type { FetchPluZoneOptions, PluExplanation } from "./enrichment/plu.ts";
export { getZonePatrimoine } from "./enrichment/patrimoine.ts";
export type { ZonePatrimoine, PatrimoineCategorie } from "./enrichment/patrimoine.ts";
export { fetchTaxeFonciere } from "./enrichment/taxe-fonciere.ts";
export type { FetchTaxeFonciereOptions } from "./enrichment/taxe-fonciere.ts";
export { buildQuickAnalysis, scoreLabel } from "./scoring/score.ts";
export { estimateAcquisitionCost } from "./scoring/acquisition.ts";
export type { AcquisitionCost } from "./scoring/acquisition.ts";
export { resolveAddress } from "./resolver/index.ts";
export type { ResolverInput, ResolvedAddress, MatchBreakdownItem } from "./resolver/types.ts";
