export * from "./types";
export type { Repository, CacheEntry } from "./storage/repository";
export { isLeboncoinListingPage, parseLeboncoin, parseLeboncoinHtml } from "./extraction/leboncoin";
export { detectSite, isListingPage } from "./extraction/sites";
export { isSelogerListingPage, parseSeloger, parseSelogerHtml } from "./extraction/seloger";
export { parseBienici } from "./extraction/bienici";
export { isCityaListingPage, parseCitya } from "./extraction/citya";
export { detectCommuneDoubt } from "./extraction/commune-doubt";
export type { CommuneDoubt } from "./extraction/commune-doubt";
export { geocode, geocodeSuggest, correctedLocation } from "./enrichment/geocode";
export type { GeocodeSuggestOptions } from "./enrichment/geocode";
export { stripAccentsLower, fixMojibake } from "./extraction/mapping";
export { parseDvfCsv, computeMarketStats, fetchCommuneSales, DVF_YEARS, haversineM, propertySaleHistory, buildSaleTimeline } from "./enrichment/dvf";
export type { SaleTimeline } from "./enrichment/dvf";
export { fetchRisks } from "./enrichment/risks";
export type { FetchRisksOptions } from "./enrichment/risks";
export { fetchCommuneInfo, citycodeFromLatLon, postalCodeOfCity } from "./enrichment/commune";
export type { FetchCommuneInfoOptions } from "./enrichment/commune";
export { fetchPluZone, explainPluZone } from "./enrichment/plu";
export type { FetchPluZoneOptions, PluExplanation } from "./enrichment/plu";
export { fetchTaxeFonciere } from "./enrichment/taxe-fonciere";
export type { FetchTaxeFonciereOptions } from "./enrichment/taxe-fonciere";
export { buildQuickAnalysis, scoreLabel } from "./scoring/score";
export { estimateAcquisitionCost } from "./scoring/acquisition";
export type { AcquisitionCost } from "./scoring/acquisition";
export { resolveAddress } from "./resolver";
export type { ResolverInput, ResolvedAddress, MatchBreakdownItem } from "./resolver/types";
